# Generated by Django 2.2.7 on 2019-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
