# Generated by Django 2.2.7 on 2019-11-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='video_link',
        ),
        migrations.AddField(
            model_name='project',
            name='web_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
